apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  my.cnf: |
    [mysqld]
    server-id=1
    log_bin=mysql-bin
    binlog_format=row
    enforce-gtid-consistency=1
    gtid-mode=ON
    log_slave_updates=1
    read_only=0
